### PR TITLE
37 Simplify API

### PR DESCRIPTION
**Pull request by zaboco**
Solving #37 

Trying to make the API as simple as possible, without loosing functionality. 

[CHANGELOG entry](https://github.com/zaboco/elm-draggable/blob/37-simplify-api/CHANGELOG.md#400-simplified-api)

Adapted `elm-package diff` output:
```diff
====== Removed modules - MAJOR ======

- Draggable.Events


====== Changes to module Draggable - MAJOR ======

____ Added:
+ type DragEvent
+   = Click
+   | DragBy Draggable.Delta
+   | DragEnd
+   | DragStart
+ eventSubscriptions : 
+   (Draggable.State -> Draggable.DragEvent -> msg) 
+   -> Draggable.State 
+   -> Sub msg

____ Removed:
- type Config a msg
- type Msg a
- type alias Event a msg = Internal.Event a msg
- basicConfig : (Draggable.Delta -> msg) -> Draggable.Config a msg
- customConfig : List (Draggable.Event a msg) -> Draggable.Config a msg
- update : Draggable.Config a msg -> Draggable.Msg a -> ...

____ Changed:
- customMouseTrigger : Decoder a -> (Draggable.Msg () -> a -> msg) -> Property msg
+ customMouseTrigger : Decoder a -> (Draggable.State -> a -> msg) -> Property msg

- init : Draggable.State a
+ init : Draggable.State

- mouseTrigger : a -> (Draggable.Msg a -> msg) -> Property msg
+ mouseTrigger : (Draggable.State -> msg) -> Property msg

- subscriptions : (Draggable.Msg a -> msg) -> Draggable.State a -> Sub msg
+ subscriptions : (Draggable.State -> Draggable.Delta -> msg) -> Draggable.State -> Sub msg
```

Remarks:
- Tests were temporarily removed, because they were no longer working with the new API. New tests were made in #38, which will be merged after this one.

### CODE REVIEW

**Comment by zaboco** [comment]
@ggazzi @crazymykl If you have some time, I would appreciate some feedback, since there are big API changes. See the [CHANGELOG](https://github.com/zaboco/elm-draggable/blob/37-simplify-api/CHANGELOG.md#400-simplified-api) for details.

**Comment by crazymykl** [comment]
On Monday 'll port our app to the new API and report back any points of friction (or missing functionality).

**Comment by ggazzi** [comment]
I've ported my app to the new API without much difficulty. The migration path described on the changelog helped a lot!

The new API seems equivalent to the old one in terms of functionality, and a lot clearer and easier to use. Handling drag events with an `updateOnDrag` function feels more familiar than writing a `Config`, and the suggested  `TriggerDrag` and `UpdateDrag` events make it easy to understand when each event might happen.

The only point of friction I (still) had was when handling multiple targets. In this case, the user needs to store the "target of the next drag event" received from a `TriggerDrag`. Ideally, the `DragStart` and `Click` events would contain all the information about their target. On the other hand, this separation allows _a lot_ of flexibility when needed, while keeping the simple cases simple, so I think that's the right tradeoff.

Also, thanks for the excellent documentation!

**Comment by zaboco** [comment]
@ggazzi Thanks a lot for the feedback, I'm glad that you've found the documentation helpful. You're right about the trade-off made for multiple targets, I've thought about that too and, as you said, i think is better to favor flexibility, and it seems to be a good practice to hold as little state in the library as possible.

One thing that I'm not quite sure about is whether to keep the subscriptions naming as it is (`subscriptions` / `eventSubscriptions`) or to change the view-point and rename to (`basicSubscriptions` / `subscriptions`), assuming that event subscriptions is the more common case. cc @crazymykl

**Comment by ggazzi** [comment]
Between those two, I actually prefer (`subscriptions` / `eventSubscriptions`), for `eventSubscriptions` clearly expresses its intent.

Another option would be dropping the assumption about which function is more common, and naming them (`basicSubscriptions` / `eventSubscriptions`). We lose a bit of conciseness, but I think the role of each function becomes clearer: `eventSubscriptions` will give me a few different events, and `basicSubscriptions` will give me less detail.

**Comment by zaboco** [comment]
> Another option would be dropping the assumption about which function is more common, and naming them (basicSubscriptions / eventSubscriptions).

Yes, that's a very good idea.

**Comment by crazymykl** [comment]
I feel like I'm getting significantly degraded performance with the new version, and dragEnd messages are sometimes not fired. Will investigate further.

Update: I was able to fix the `DragEnd` not being respected issue, but the performance still seems worse. I think a minor architectural change to my app might help, though...

**Comment by crazymykl** [comment]
It seems like the slowness is largely due to the new code causing _way_ more GCs...

**Comment by zaboco** [comment]
> It seems like the slowness is largely due to the new code causing way more GCs...

@crazymykl Interesting, I did not expect this change to affect the performance. How can I see how many GCs are made, what method did you use to measure that?

**Comment by crazymykl** [comment]
Just to make sure, I went back to 3.0.0, and I can drag things in quick squiggles for 15 solid seconds without the mouse desyncing or a super-noticable GC pause. On 4.0.0, I cannot do that.

**Comment by crazymykl** [comment]
I used Firefox's performance profiling tool, and each time it lagged, I could see the framerate dip and a "Non-Incremental GC" run.

**Comment by zaboco** [comment]
@crazymykl I could not reproduce on latest Firefox on OS X, with `CustomEventsExample` (Is it too simple to be a good use case?). It went smoothly when not recording for profiling. Indeed was a bit laggy when recording, but that was the case for the 3.0.0 version too. And when recording, I only got 'minor' and 'incremental' GC, none was 'non-incremental'.

Also, on Chrome and Safari it works very well too. Did you try on any other browser too?

**Comment by crazymykl** [comment]
IE is worse than FF, Safari and Chrome are better. My use case involves dozens of draggable things, plus clicking/dragging on empty space clears it.

The performance wouldn't be a dealbreaker if it didn't mean that the dragged things fall out of sync with the mouse.

**Comment by YetAnotherMinion** [comment]
I was inspired by the example code on #37 and quickly wrote a drag abstraction that works with my personal project.

Important for me is the ability to register what is being dragged. It is not clear to me on the new API if that is possible. It looks like you would have to create a custom Decoder that was partially applied to contain the data you wanted???

``` elm
module Drag exposing
    ( State, Msg(Start, Moved, End, Click), onMouseDown, subscriptions, update
    , init
    )


import VirtualDom
import Mouse exposing (Position)
import Json.Decode


type State interactionLocation
    = MouseDown interactionLocation Position
    | MouseMoved interactionLocation Position
    | NotDragging

init : State interactionLocation
init =
    NotDragging

type Msg interactionLocation
    = Start interactionLocation Position
    | Moved interactionLocation Position Delta
    | End interactionLocation Position Delta
    | Click interactionLocation Position

type alias Delta = (Int, Int)

update : Msg interactionLocation -> State interactionLocation -> State interactionLocation
update msg model =
    case msg of
        Start location xy ->
            MouseDown location xy

        Moved location xy (dx, dy) ->
            MouseMoved location xy

        End location xy (dx, dy) ->
            NotDragging

        Click location xy ->
            NotDragging
             

onMouseDown : VirtualDom.Options -> location -> VirtualDom.Property (Msg location)
onMouseDown options interactionLocation =
    VirtualDom.onWithOptions "mousedown"
        options
        (Json.Decode.map (\p -> Start interactionLocation p) Mouse.position)


subscriptions : State interactionLocation -> Sub (Msg interactionLocation)
subscriptions lastState =
    case lastState of
        MouseDown location xy ->
            Sub.batch
                [ Mouse.moves (\p -> Moved location p (p.x - xy.x, p.y - xy.y))
                , Mouse.ups (\p -> Click location p)
                ]

        MouseMoved location xy ->
            Sub.batch
                [ Mouse.moves (\p -> Moved location p (p.x - xy.x, p.y - xy.y))
                , Mouse.ups (\p -> End location p (p.x - xy.x, p.y - xy.y))
                ]

        NotDragging ->
            Sub.none
```
I use it the normal elm components way

```elm
import Drag

-- wrap its model inside my model
type alias Model =
    { drag = Drag.State InteractionLocation
    --....
    }

type InteractionLocation
    = OnTriangle Int
    | OnRectangle Int
    | OnBackground

-- wrap its messages inside my messages
type Msg
    = NoOp
    | DragMsg (Drag.Msg  InteractionLocation)

-- write a wrapper update setter for my specific model
updateDrag : Drag.Msg InteractionLocation -> Model -> Model
updateDrag dragMsg model =
    { model | drag = Drag.update dragMsg model.drag }

-- use pattern matching to unwrap its messages in my update
update : Msg -> Model -> Model
update msg model =
    case msg of
        NoOp ->
             model ! []

       DragMsg (Drag.Start location xy as dragMsg) ->
            updateDrag dragMsg model ! []

       DragMsg (Drag.Moved location xy (dx, dy) as dragMsg) ->
            case location of
                 OnTriangle index ->
                     model |> translateTriangle index (dx,dy) |> updateDrag dragMsg ! []

                 OnRectangle index ->
                     -- mess with them by inverting axis
                     model |> translateRectangle index (dx, -dy) |> updateDrag dragMsg ! []

                 OnBackground ->
                     model |> translateBackground (dx,dy) |> updateDrag dragMsg ! []

      DragMsg (Drag.Click location xy as dragMsg) ->
           case location of
                 OnTriangle index ->
                     model |> toggleTriangleColor index |> updateDrag dragMsg ! []

                 OnBackground ->
                     model |> resetColors |> updateDrag dragMsg ! []

                 _ ->
                     model ! []

        _ ->
           model ! []

-- Add it to your subscriptions
subscriptions : Model -> Sub Msg                                                
subscriptions model =                                                           
    Sub.batch                                                                   
        [ Sub.map DragMsg (Drag.subscriptions model.drag)                       
        --, Sub.map KeyboardExtraMsg Keyboard.Extra.subscriptions   
        -- ... etc              
        ] 

-- add mouseTriggers to html elements
onTriangleMouseDown : Int -> Attribute Msg                                          
onTriangleMouseDown index =                                                         
    let                                                                         
        options =                                                               
            { stopPropagation = True, preventDefault = True }                                      
    in                                                                          
        Html.Attributes.map DragMsg (Drag.onMouseDown options (OnTriangle index)) 

onBackgroundMouseDown : Attribute Msg                                          
onBackgroundMouseDown =                                                         
    let                                                                         
        options =                                                               
            { stopPropagation = True, preventDefault = True }                                                                 
    in                                                                          
        Html.Attributes.map DragMsg (Drag.onMouseDown options OnBackground) 

view : Model -> Html Msg
view model =
    div [ onBackgroundMouseDown ]
        [ div [ onTriangleMouseDown 4 ]
            [ text "I am a triangle (event though it doesn't look like it)" ]
        ]

```

**Comment by zaboco** [comment]
@YetAnotherMinion Yes, it is possible to register the drag target. See [this part of the CHANGELOG](https://github.com/zaboco/elm-draggable/blob/37-simplify-api/CHANGELOG.md#multiple-targets) or [a complete example](https://github.com/zaboco/elm-draggable/blob/37-simplify-api/examples/MultipleTargetsExample.elm).

For your example, it would be something like:
```elm
type Target
    = Triangle Int
    | Background

type Msg
    = TriggerDrag Target Draggable.State
    | UpdateDrag Draggable.State DragEvent

onTriangleMouseDown : Int -> Attribute Msg
onTriangleMouseDown index =                                                         
    Draggable.mouseTrigger (TriggerDrag <| Triangle index)
        
onBackgroundMouseDown : Attribute Msg                                          
onBackgroundMouseDown =                                                         
    Draggable.mouseTrigger (TriggerDrag Background)
```

Anyway, as you see in this thread, there are performance issues with this approach, so the will probably change.

**Comment by zaboco** [comment]
@crazymykl I'll investigate more when I find some time.

**Comment by crazymykl** [comment]
By restructuring my app, I was able to reduce the GC pauses but not eliminate them. However, the pauses still cause the dragged item to desync from the cursor, which will instafail QA.

**Comment by crazymykl** [comment]
Interestingly, it seems like on retest with more modern browsers, the problem is gone.

**Comment by zaboco** [comment]
@crazymykl Cool then, I'll make some time to merge this, I've almost forgot about it 😅

**Comment by crazymykl** [comment]
This is obsolete af.

**Comment by zaboco** [comment]
@crazymykl Yes, I'am aware. It's my fault, I did not merge this when I should have done it, long before 0.19 was released. Now, with 0.19, it's more difficult. And as the time I'm able to allocate to Elm projects is limited right now, I'm not sure when I'll be able to finish this. 
I'm sorry that you folks invested time in testing this, and then I abandoned it, it was not so nice on my side.

**Comment by zaboco** [comment]
Closing this for now

**Pull request closed without merging**
