### PR TITLE
Custom mouse trigger

### PR DESCRIPTION
**Pull request by zaboco**
Solving #32

### CODE REVIEW

**Comment by crazymykl** [comment]
It would be nice to have this info about where the thing was dropped, not just where it was picked up.

**Comment by zaboco** [comment]
@crazymykl Couldn't this be done with a `VirtualDom.onWithOptions "mouseup"` handler on the element? 

I agree that this does not take into account a click without a drag, and that it might be useful to pass a decoder to `onDragEnd`. However, I don't know how that could be done, since `onDragEnd` uses `Mouse.ups` sub, which only provides a `Position`, it does not have a custom form with a decoder.

**Comment by crazymykl** [comment]
That's basically what I'm doing now; I'd like a more elegant interface, having multiple types of handlers operating through different mechanisms is not ideal.

**Comment by zaboco** [comment]
@crazymykl I've opened #35, I'll think of an API for that, if you have any idea, please add a comment to that issue.

**Comment by zaboco** [comment]
published as [2.1.0](http://package.elm-lang.org/packages/zaboco/elm-draggable/2.1.0)

**Pull request merged**
