### PR TITLE
Add touch support

### PR DESCRIPTION
**Pull request by abingham**
This adds the 'touchTriggers` function for add touch support alongside mouse support.

### CODE REVIEW

**Review by zaboco — APPROVED** [review]
Looks great, I've tested on an actual phone and it works.
You just need to merge master into your branch, to make travis build work again. Thanks a lot! 👍

**Comment by zaboco** [comment]
> You just need to merge master into your branch, to make travis build work again.

Nevermind, it seems I had the rights to do that myself.

**Comment by zaboco** [comment]
closes #41

**Comment by zaboco** [comment]
closes #25 
published in [3.1.0](http://package.elm-lang.org/packages/zaboco/elm-draggable/3.1.0)

**Comment by abingham** [comment]
Awesome, thanks!

**Pull request merged**
